### PR TITLE
Separate language files #445

### PR DESCRIPTION
**Pull request by JHCD**
Separate the language files to avoid breaking all translations by one mistake.
See discussion #445 and e.g. for an issue #367

- [x] ~~cqui.modinfo (possible/usefull?)~~
- [x] CQUI general
- [x] CQUI settings
- [x] Better Trade Screen
- [x] Unit Report Screen
- [x] Improved Deal Screen
- [x] More Lenses

Do we want to separate all the integrated mod textfiles?
Are they original or created by us?

### CODE REVIEW

**Comment by chaorace** [comment]
modinfo won't be possible to separate, but that's inconsequential considering how little there is to localize in it. I vote yea to fully breaking apart the LOC files, even in the mod integrations. For the most part, we do all our own localisations anyways, so I see no major issue further mangling these files

**Comment by JHCD** [comment]
Is there a possibility to change the language in Civ?
Otherwise I could have checked only the german version.

**Comment by chaorace** [comment]
Yes, it's a game setting. Anyways, I plan to review this today, but won't merge it until after the workshop patch, since this specific change has lots of breaking potential but doesn't bring anything new immediately

**Comment by JHCD** [comment]
Why cqu_text_settings.xml isn't able to automerge anymore?
Since yesterday it works and the last commit in master is 1 month ago...

**Pull request merged**
