### PR TITLE
Spring 2017 Patch

### PR DESCRIPTION
**Pull request by JHCD**
Pull request with the updates coming with the Spring 2017 patch.

4 Files are left, looks like (some) changes should taken over, but I can't decide it.
- [x] UI/Panels/ProductionPanel.lua
Diffs: https://github.com/chaorace/Civ6-UIFiles/commit/34763b90249c0f7545a954b6e3b4b0678a81f5e2#diff-d96026e108fd59e6ae0faf23133115e7
- [ ] UI/Panels/StatusMessagePanel.lua
Diffs: https://github.com/chaorace/Civ6-UIFiles/commit/34763b90249c0f7545a954b6e3b4b0678a81f5e2#diff-1907ed78559b93621b9c31ec444d3a0c
- [ ] UI/Panels/StatusMessagePanel.xml
Diffs: https://github.com/chaorace/Civ6-UIFiles/commit/34763b90249c0f7545a954b6e3b4b0678a81f5e2#diff-8bc50f12e679ea44c264cc11fdfc2123
- [x] UI/ToolTips/PlotToolTip.lua
Diffs: https://github.com/chaorace/Civ6-UIFiles/commit/34763b90249c0f7545a954b6e3b4b0678a81f5e2#diff-8894ea8c4643ba0618533acd48ce66e7

### CODE REVIEW

**Comment by ProustIdee** [comment]
I will go through more later, but using a 3 way merge, in PlotToolTip.lua there's actually only one new change from the Australia Update to the Spring Update, relative to CQUI:

image

Not sure how to add that to this pull request?

**Comment by JHCD** [comment]
The *how* is clear. But I don't know if there is a reason, that the if block is missing, or only forgotten...

**Comment by chaorace** [comment]
This was probably just missed, looks fine to add in

**Comment by JHCD** [comment]
Okay, three left ;)

**Comment by ProustIdee** [comment]
I think this is it for statusmessagepanel.lua ?

image

**Comment by JHCD** [comment]
Yeah, but trying to change the statusmessagepanel.xml brake it down to empty boxes. :-o

**Comment by JHCD** [comment]
Link to #481

**Comment by ricanuck** [comment]
1. is done.

**Comment by JHCD** [comment]
@chaorace Hi Chris, could you merge the commits into master and let this PR open for the last 2 files?
If not, please merge this PR and I will open an ToDo-Issue. I will no longer "wait" for the patches only why we haven't finished this 2 files.

**Comment by chaorace** [comment]
Okay, I've merged the existing commits into master. Keep in mind that they've been consolidated into a single commit, so this PR will need to be rebased upon master and have all commits beside 523818b9f3380b695528ccb9bf2cd70115e58e21 removed from the history before it can be merged upon completion of the last few straggling files

**Comment by JHCD** [comment]
No problem for me to open a new PR / issue to keep the complexity small

**Comment by SpaceOgre** [comment]
StatusMessagePanel are throwing error since there is no element named Button, after this merge. I think the reason they changed from grid to grid button is to enable players to remove the message by clicking on it. If we want to incorporate this I think we can just change the grids in question and change Button to StatusGrid (or what the id is for the grid) in the Lua file.

**Comment by SpaceOgre** [comment]
@chaorace you fixed the StatusMessagePanel right? If so I think this PR can be closed.

**Comment by chaorace** [comment]
Yeah, StatusMessage is fixed up, I guess that's the last item on this PR!

**Pull request closed without merging**
