### PR TITLE
Resolves #523.

### LINKED ISSUE #523: IDS: traded items - rounds left
It would be nice if the tooltip shows the left rounds for a traded ressource.

### PR DESCRIPTION
**Pull request by ricanuck**
Adds turns left to imported resources in IDS deals page. Resolves #523.

(I'mmm baaa-aack!)

### CODE REVIEW

**Comment by ricanuck** [comment]
My comments are all around the new code snippet. I wouldn't add any more Aristos comments there, they are a lot already for that file.

**Comment by chaorace** [comment]
@ricanuck The once and future king has graced us with his presence 😃. I'll be checking this out very soon! As long as I've got you around, consider visiting the new discord server: https://discord.gg/YUXRR32

@bolbass For the most part, comment style guidelines are only strictly enforced for base-game files, especially for shorter tweaks like these.

**Comment by ricanuck** [comment]
@chaorace , who is that one and future king? You lost me there.

I will try and stay around, not that I left, I was just busy with many things going on at the same time. I will try and contribute more now, hopefully close to what it was before.

**Comment by chaorace** [comment]
That was a compliment! Your contributions are always appreciated, but please don't feel pressured or obligated

**Comment by ricanuck** [comment]
Oh, OK! I am the once and future King! Hehe, thank you, didn't catch that one...

No worries, no pressure, I love working on projects like this, UI is so important for games like 4X (especially 4X), that it makes you wonder what the heck is Firaxis thinking when they release sub-par UIs like this one... anyways, that's our opportunity.

**Pull request merged**
