### PR TITLE
Make city markers on the minimap smaller.

### PR DESCRIPTION
**Pull request by apskim**
This PR reduces the size of giant square city markers on the minimap. This is one of the oft-requested features on /r/civ and other communities.

Screenshot:
minimap

Special thanks to NQ EUI, which already has this feature implemented, and which gave me an idea to add this to CQUI.
(Note: Should I add HellBlazer to the acknowledgments?)

### CODE REVIEW

**Comment by JHCD** [comment]
Is that selectable via CQUI config?

**Comment by apskim** [comment]
Not at the moment. I can add a toggle to the settings.

**Comment by apskim** [comment]
@JHCD Actually, I'm not sure if it's possible to control. This is not a Lua change, it's a tweak in the artdefs, which are unconditionally loaded by the game.

**Comment by chaorace** [comment]
I'm fairly certain this won't be possible to adjust at all. I'm pretty sure nobody is happy with the current blip size, so I think scaling it down is warranted, however, since it's likely not going to be possible to adjust, I think we should look to strike a healthier middle ground than the somewhat small size shown here

**Comment by apskim** [comment]
@chaorace 20 is actually not far away from 22, which is what the base game has. I can't notice any difference when the whole map is revealed.

**Comment by pspjuth** [comment]
I think 11 was a better choise. On the screenshot it is still early and looks a bit weird, but on a fully revealed small map, 11 is roughly the size of a tile.

**Comment by chaorace** [comment]
Alright, you've been heard. I like 11 too, but this won't be adjustable and I know people will complain if we make it _that_ small. I'll set it to 14 and see how the feedback is

**Comment by astog** [comment]
@alexpolozov I know this is late, but kudos on figuring this out. I have been trying to do find a solution to this for so long. 👍

**Pull request merged**
