### PR TITLE
Incorporate NQ EUI LaunchBar tweaks

### LINKED ISSUE #485: LaunchBar Improvements from HellBlazer's NQ Enhanced User Interface
Watched HallBlazer's stream tonight as he was adding stuff to his NQ Enhanced User Interface, and think we could incorporate some of the things he have done to the launch bar. Mostly I'm thinking about moving the Reports button there, but also when the world tracker is hidden show the tech/civ currently researching with timer circle.

image

What do you think?

### PR DESCRIPTION
**Pull request by SpaceOgre**
Not sure what happend to the WorldTracker.lua diff, it went crazy. To see changes for this file look at the individual commits.

resolves #485

### CODE REVIEW

**Comment by JHCD** [comment]
1.) Do you have cross-checked, that the the files this mod integrates in CQUI is on the Spring Patch level?
2.) Shouldn't the new files not stored in /integrations/?

**Comment by SpaceOgre** [comment]
1. Yes they should be since I copied them from my install that is on the Spring Patch
2. I guess they maybe should be in integrations? But I'm not sure since some of the changes are in files we already have and then it would be spread out. And I didn't copy his code straight off but rather I copied the vanilla files and did my own changes with his code as a bit of guide.

**Comment by JHCD** [comment]
Perfect. ;)

Okay, seem like it is not very usefull to put half of the files in this integration folder.
We should do it similar to /integration/pq... reference to NQEUIs homepage

**Comment by SpaceOgre** [comment]
Thanks for testing. Should be fix now.

**Pull request merged**
